import numpy as np
import pandas as pd

arr = np.array([1,2,3,4])
sex = pd.Series(['Male', 'Male', 'Female'])
sex = np.array(sex)
print(arr, sex)
arr = np.linspace(10,100,4).astype(int)
print(np.array2string(arr))
arr = np.arange(5.3,10,1.3)
print(arr)
arr = np.random.uniform(0,1,3)
print(arr)
arr = np.random.uniform(0,1, size= (2,3))
print(arr)
arr = np.zeros((1,20), dtype="int")
print(arr)
arr = np.ones((3,4))
print(arr)
arr = np.random.uniform(1,24,13)
print(arr)
print(arr.min())
print(np.min(arr), np.max(arr), np.unique(arr), np.mean(arr), np.median(arr))
sex = pd.Series(['Male', 'Male', 'Female'])
print(sex.describe())